### ISSUE TITLE
Parameter registration fail.

### ISSUE THREAD

**Issue by xsmarty** [yamcs/yamcs#104]
Client uses "RestListAvailableParametersResponse" to get all available parameters via REST. 
However, Websocket subscription will fail for a few of them. (mostly due to no "simulator" on the server side). 
Rest parameter request is fine and returns empty data.

Expected behaviour : 
Subscription succeeds for every parameter listed as available. No data is send from server to client if server has 0 data available in websocket mode.

**Comment by xpromache** [comment]
This issue  (if there was any issue actually) should be fixed by now. 
Please reopen if it is not.
