### ISSUE TITLE
minimumTcPacketLength config parameter parsed incorrectly

### ISSUE THREAD

**Issue by bitblit11** [yamcs/yamcs#141]
The minimumTcPacketLength parameter in the tcp.yaml configuration file is not being parsed correctly and always defaults to 48.

In the org.yamcs.tctm.TcpTcUplinker::TcpTcUplinker(String yamcsInstance, String name, String spec) constructor, the key to the minimumTcPacketLength parameter is '"tcp."+spec+".minimumTcPacketLength"'.  This should be changed to "minimumTcPacketLength".

**Comment by xpromache** [comment]
fixed by commit 4aee6d3774c4797b71d9b0a4db0dcd559d10defd
