### ISSUE TITLE
Condition statements in the .xls should use double equals, not single equals for comparison

### ISSUE THREAD

**Issue by tomvanbraeckel** [yamcs/yamcs#182]
In the .xls files, there are several columns with condition statements, such as the "Transmission Constraints" on the CommandOptions tab of leo-spacecraft.xls

In these columns, conditions such as "AllowCriticalTC1=true" can be found.

The above example statement looks more like an assignment than a condition. Also, the recommended way to specify an equals condition is to use == (double equals), not = (single equal).

**Comment by xpromache** [comment]
implemented in 3.3 (both = and == are allowed now for compatibility with the older versions)
