### ISSUE TITLE
Commanding: free text description to issued command

### ISSUE THREAD

**Issue by m-sc** [yamcs/yamcs#183]
The purpose is to have a free text description associated to a command that is being issued, or that is already issued.

Todo:
- Add optional field "description" to IssueCommandRequest protobuff message and API.
- Save description in command history a regular field, named "description".
- Add a REST API to update/add a command history field (if a user want to add a description after the command has been issued).
- Ensure that a privilege "Update Command History" is requested to update the command history via the REST API.

**Comment by fqqb** [comment]
Closing as this was resolved quite a while ago already.
