### ISSUE TITLE
WebSocket API - Parameter Updates: unsubscribeAll only possible when the user did a subscribeAll

### ISSUE THREAD

**Issue by kstruyven** [yamcs/yamcs#210]
When subscribing to a Parameter Update with the WebSocket API, you have to provide the parameter name/namespace when you want to unsubscribe from it. 
If the user is subscribed to multiple parameters, multiple messages have to be sent in order to unsubscribe from all of them because the unsubscribeAll message is only supported when the user selected subscribeAll at the beginning.
It would be useful if unsubscribeAll would always be available and unsubscribe the user from all his subscribed parameters.

**Comment by xpromache** [comment]
Fixed in yamcs 4.0.0 commit  77add1fb24b34ac0c4b5de65ec1e1025ddcea24e
