### ISSUE TITLE
EventViewer shows event details of wrong event when sorted

### ISSUE THREAD

**Issue by tomvanbraeckel** [yamcs/yamcs#211]
The YaMCS Event Viewer shows event details of the wrong event when the view is sorted by a column other than "reception time". 

Reproduction:
- start the YaMCS Event Viewer
- connect to an active YaMCS server (asim-gm for instance)
- wait until some events come in
- sort by "Source" or "Type"
- double-click an event

Result: the event details that are shown will be of a different event

Expected result: the event details that are shown are the details of the event that was double-click'd

**Comment by fqqb** [comment]
This was fixed a while ago
