### ISSUE TITLE
EventViewer does not show incoming events after sorting and clearing

### ISSUE THREAD

**Issue by tomvanbraeckel** [yamcs/yamcs#212]
The YaMCS Event Viewer does not show incoming events when the view has been sorted by a column and cleared.

Reproduction:
- start the YaMCS Event Viewer
- connect to an active YaMCS server (asim-gm for instance)
- wait until some events come in
- sort by "Source" or "Type"
- click "View" - "Clear"
- wait until more events come in

Result: the "Total events" counter increases but the event list stays empty

Expected result: the "Total events" counter increases and the new events are added to the event list

**Comment by fqqb** [comment]
This was fixed a while ago.
