### ISSUE TITLE
Yamcs packet viewer shows packets multiple times after disconnect/reconnect

### ISSUE THREAD

**Issue by tomvanbraeckel** [yamcs/yamcs#238]
It is noticed that in case the packet viewer is not closed at the end of a session, each time the VPN is reestablished, the received packets are shown an additional time.

So if the connection is lost 3 times, each packet is displayed 3 times.

A short term solution is to add in the ground procedures to close the Yamcs Packet Viewer after every disconnection but that adds some overhead and it's probably a small fix to have it not duplicate the packets after disconnection...

**Comment by fqqb** [comment]
Fixed for next release. It was bug in the client where a new listener was added on each reconnect.
