### ISSUE TITLE
Yamcs web interface: MDB/Parameters/Chart - timestamp missing when hovering over chart

### ISSUE THREAD

**Issue by kstruyven** [yamcs/yamcs#276]
When hovering over a chart of a MDB parameter, it only shows the value but not the timestamp. This makes it impossible to get a value at a specific time.

![screenshot from 2018-09-10 14-16-54 002](https://user-images.githubusercontent.com/24792401/45304413-597ce500-b518-11e8-9963-4eba9fc9a3e6.png)

**Comment by fqqb** [comment]
Thanks for the issue. I'll work on this. Probably will be via a timestamp indicator displayed on the x-axis that moves together with the vertical mouse locator.

**Comment by fqqb** [comment]
Implemented in #279 Example:

![image](https://user-images.githubusercontent.com/145170/45472525-c4a30300-b734-11e8-922e-64aad5794df8.png)

**Comment by fqqb** [comment]
Merged on master. This will be in the next 4.x release.
