### ISSUE TITLE
Event Viewer: sorting makes it open the wrong "event details"

### ISSUE THREAD

**Issue by tomvanbraeckel** [yamcs/yamcs#277]
In the standalone Event Viewer, when the columns are sorted by a different column than the default, double-clicking on an event to see the details shows the details of a different event.

It seems that the "double-click to show event details" logic does not take into account the non-default sorting and shows the details of the event that was originally in that position.

**Comment by tomvanbraeckel** [comment]
Yes, sorry I didn't specify. It was indeed with Yamcs Event Viewer v3.4.x.

**Comment by fqqb** [comment]
Fixes duplicated on 3.4.x in pr #280
Once merged, see with @xpromache if you'd like a new 3.4.x release.

**Comment by fqqb** [comment]
Merged on 3.4.x branch
