### ISSUE TITLE
yamcs-web and archive tags

### ISSUE THREAD

**Issue by vinnitu** [yamcs/yamcs#299]
Do you have any plans to append support archive tags in web client? 
https://www.yamcs.org/docs/http/Tags/

It is very needed functionality for us in "Monitor -> TM Archive" tab with link REPLAY RANGE and DONLOAD DUMP

![image](https://user-images.githubusercontent.com/432168/50212246-3bc6e380-0383-11e9-8000-6ef2741ed2d3.png)

**Comment by fqqb** [comment]
I can have a look at this once #305 is resolved

**Comment by vinnitu** [comment]
![image](https://user-images.githubusercontent.com/432168/50970568-66234100-14ea-11e9-82f3-2e9f78615611.png)

We trying to implement tags functionality, do you interested to get it? Maybe you have more competent vision about it?

**Comment by fqqb** [comment]
That's great, I'll not touch this then. 

I'm curious why a different page, I would argue it's useful to show tags together with the packet ranges, but all in one single band. This is what we do in Yamcs Studio (orange boxes are tags):

![image](https://user-images.githubusercontent.com/145170/50971896-7f75be80-14e5-11e9-9c89-f17fa51bdfc8.png)

The timeline widget supports wrapping boxes in the same band (option `wrap: true`).

**Comment by vinnitu** [comment]
![image](https://user-images.githubusercontent.com/432168/50987992-d4c8c480-1513-11e9-9302-49465460c0b9.png)

version without wrapping

**Comment by fqqb** [comment]
Closing as we no longer plan to support edit of tags on yamcs-web. Only read-only is implemented for legacy reasons.

Instead we are working towards a more feature-full timeline solution. This work is currently on separate branch (server parts only): https://github.com/yamcs/yamcs/tree/timeline
