### ISSUE TITLE
lightblue

### ISSUE THREAD

**Issue by vinnitu** [yamcs/yamcs#312]
Hello, what does lightblue mean?

![image](https://user-images.githubusercontent.com/432168/51825306-22ec0f00-22ed-11e9-89d0-dd59b856b01a.png)

**Comment by xpromache** [comment]
The values shown there are (average, min, max) for each equally sized
interval where the length of the interval is determined by the total time
of the graph divided by the interval count.
This is the call that is being used:
https://www.yamcs.org/docs/http/Get_Parameter_Samples/

The average is shown in dark blue whereas the min/max are shown as a
vertical line in light blue.

**Comment by vinnitu** [comment]
As I understand it is {errorBars: true} option in dygraph http://dygraphs.com/options.html#Error%20Bars

**Comment by fqqb** [comment]
it uses dygraphs customBars using (min, avg, max) for each sample interval.
