### ISSUE TITLE
strange behavior

### ISSUE THREAD

**Issue by vinnitu** [yamcs/yamcs#313]
![peek 2019-01-28 11-22](https://user-images.githubusercontent.com/432168/51826172-149ef280-22ef-11e9-8374-e65e1cac1374.gif)

how to interpret changes of graph?

**Comment by xpromache** [comment]
That is because when data is downloaded from the archive, it uses (avg,min,max) whereas when data is appended in realtime, all points will be added.
This is something we should probably fix.

**Comment by vinnitu** [comment]
yes, I see

**Comment by fqqb** [comment]
To be complete, realtime data uses a separate buffer, which --when almost full-- will trigger a full refresh of the graph (ad infinitum).

Not sure how else we can make this work.
