### ISSUE TITLE
geomap widget

### ISSUE THREAD

**Issue by vinnitu** [yamcs/yamcs#314]
Hello!

Suppose we need some widget to display trajectory of object.

I like https://youtu.be/ibv6vcNrxzA?t=50 video from https://cesiumjs.org/demos/FlightClub/

![image](https://user-images.githubusercontent.com/432168/52267972-0b430500-2943-11e9-9641-ba791fc1ecda.png)

We have described ccsds-packets with geo-location and altitude.
We need setup start location and flight polygon described set of geo points (in easy case it is just start point, azimuth and length of flight field). 

Also we want to send alert when object become outside of this polygon. It maybe algorithm in tab Algorithms in landing.xls.

Question is where save this polygon dataset? 
Can we use local params to set this data? 
How algorithm get access to it?
How to reconfigure(and save) it by rest api from web-interface without restart server?

What do you think about it?

**Comment by xpromache** [comment]
The polygon dataset should be an array parameter - currently they are only
half supported and not possible to set from the user.

Maybe you can do with a long string (e.g. json for example) for the moment
and then in the algorithm split the string into numbers and do the
computation.
