### ISSUE TITLE
how to properly make unsubscription

### ISSUE THREAD

**Issue by vinnitu** [yamcs/yamcs#323]
ooook...

but, ?

![image](https://user-images.githubusercontent.com/432168/53189911-30a56380-3611-11e9-9653-c45e3eae25a1.png)

as you can see
```
[1,3,3,{"et":"STRING","msg":"Cannot find field: id in message yamcs.protobuf.NamedObjectList"}]
```

_Originally posted by @vinnitu in https://github.com/yamcs/yamcs/issues/322#issuecomment-466096413_

**Comment by fqqb** [comment]
that's a bug indeed. I'll work on a fix.
Both subscribe and unsubscribe used to use a field `list`, which was later renamed to `id` (apparently not successfully).

Possibly you can work around it by changing "id" into "list" (on unsubscribe only), but i didn't try.

**Comment by xpromache** [comment]
Fixed
