### ISSUE TITLE
Processors cannot be stopped in Yamcs Monitor by right-click and "destroy"

### ISSUE THREAD

**Issue by tomvanbraeckel** [yamcs/yamcs#338]
In Yamcs Monitor version 3.4.9, connected to Yamcs Server 3.4.9, when we create a processor (by doing "Selection" - "Export Telemetry Packets..." in the Archive Browser) and then try to destroy it by right-clicking and choosing "Destroy", the processor does not stop or get destroyed.

**Comment by fqqb** [comment]
Closing because Yamcs Monitor is unmaintained, and not anymore included in this repository.
