### ISSUE TITLE
Extending AbstractTmDataLink is not possible because packetPreprocessor is not visible

### ISSUE THREAD

**Issue by merose** [yamcs/yamcs#354]
Writing a new data link deriving from `AbstractTmDataLink` in your own package is not currently possible because there is no way to call the packet preprocessor from within the derived class. The current definition of the `packetPreprocessor` uses default scope (line 29 of AbstractTmDataLink.java):

    PacketPreprocessor packetPreprocessor;

It would be best to give this field `private` scope and add a public or protected getter, such as `getPacketPreprocessor()` to the class. Derived classes could then get the preprocessor to use before returning the packet, as is done in `UdpTmDataLink.getNextPacket()`, for example.

**Comment by xpromache** [comment]
made it protected.
