### ISSUE TITLE
Abstract metacommands in XTCE can still be sent

### ISSUE THREAD

**Issue by merose** [yamcs/yamcs#357]
To reproduce:

1. Use an XTCE command configuration that includes an abstract command.

     <xtce:MetaCommand name="BASE_COMMAND" abstract="true">
         ...
     </xtce:MetaCommand>

2. In the YAMCS web interface, go to Commanding > Send a Command.

3. Select the abstract command (BASE_COMMAND), enter any arguments, and press Send.

Actual result: Command is sent.

Expected result: User should not be able to send the abstract command. Unclear exactly what the UI should be, but perhaps the abstract commands should not be in the list of commands in the "1. Select command" step.

**Comment by xpromache** [comment]
Looks like the abstract attribute of the MetaCommand was not read from the xml, fixed with 49fa975.
