### ISSUE TITLE
Assembly plugin needs posix mode on OS X or build fails creating tar files

### ISSUE THREAD

**Issue by merose** [yamcs/yamcs#363]
Environment:
OS X 10.14.6
Maven 3.2.3

In our environment our group IDs are very large integers. Creating tar files using maven-assmbly-plugin during the build fails with an error like this "group id '2060452353' is too big ( > 2097151 ). Use STAR or POSIX extensions to overcome this limit".

The fix is to add "<tarLongFileMode>posix</tarLongFileMode>" to the configuration of maven-assembly-plugin in both distribution/pom.xml and yamcs-core/pom.xml. Note that the POM in distribution already has a different configuration value, "gnu".

See also this issue in the elastic search project: https://github.com/elastic/elasticsearch/issues/11824

**Comment by fqqb** [comment]
Thanks, I wasn't aware of these differences. "gnu" was added to avoid Maven warnings with long filenames, but it looks like the posix format also handles this correctly.
Fix included in pr #364
