### ISSUE TITLE
Any harm in setting TC link "initialDelay" to zero?

### ISSUE THREAD

**Issue by merose** [yamcs/yamcs#375]
All of the examples showing the configuration of outgoing tc links use a nonzero "initialDelay", often with a comment like this:

      # Give the embedded simulator some time to boot up
      initialDelay: 2000

Is there any reason to use a nonzero initialDelay if you are not running the simulator?

**Comment by xpromache** [comment]
no need for the initialDelay - even for the simulator is not strictly necessary but we want to avoid a "connection refused" warning at startup. The link will retry the connection.
