### ISSUE TITLE
XTCE inclusive/exclusive alarm range endpoints are interpreted the opposite way

### ISSUE THREAD

**Issue by merose** [yamcs/yamcs#379]
To reproduce, add an XTCE type that uses a DefaultAlarm with an alarm range setting. For example:

    <xtce:FloatParameterType name="SampleType" sizeInBits="64">
      <xtce:FloatDataEncoding sizeInBits="64" byteOrder="mostSignificantByteFirst" encoding="IEEE754_1985" />
      <xtce:DefaultAlarm minViolations="1" minConformance="1">
        <xtce:StaticAlarmRanges rangeForm="outside">
          <xtce:WarningRange minInclusive="1" maxExclusive="2" />
        </xtce:StaticAlarmRanges>
      </xtce:DefaultAlarm>
    </xtce:FloatParameterType>

    ...

    <xtce:Parameter parameterTypeRef="SampleType" name="sample" />

When retrieving the parameter definition using the HTTP API `/api/mdb/<instance>/parameters/.../sample`, the inclusive/exclusive definitions are opposite of the XTCE:

        "defaultAlarm": {
          "minViolations": 1,
          "staticAlarmRange": [{
            "level": "WARNING",
            "maxInclusive": 2.0,
            "minExclusive": 1.0
          }]
        }

The problem is in DoubleRange.java in `fromXtceComplement()`:

    /**
     * Returns a range from the XTCE float range used for alarms which is in fact a union of two ranges
     * @param minExclusive
     * @param maxExclusive
     * @param minInclusive
     * @param maxInclusive
     * @return
     */
    public static DoubleRange fromXtceComplement(double minExclusive, double maxExclusive, double minInclusive, double maxInclusive) {
        double min = minExclusive;
        double max = maxExclusive;
        boolean minIncl = true;
        boolean maxIncl = true;

        if(!Double.isNaN(minInclusive)) {
            min = minInclusive;
            minIncl = false;
        }
        if(!Double.isNaN(maxInclusive)) {
            max = maxInclusive;
            maxIncl = false;
        }

        return new DoubleRange(min, max, minIncl, maxIncl);
    }

The initial values of `minIncl` and `maxIncl` should be `false`, instead. And then the assignments within the if-statements should set those variables to `true`.

**Comment by xpromache** [comment]
thanks for the report, fixed.
