### ISSUE TITLE
Converting Prepended Binary to XTCE file

### ISSUE THREAD

**Issue by JoshSharpe** [yamcs/yamcs#384]
I'm working on converting my Excel mdb to an XTCE file and noticed XTCE does not natively support prepended binary but other types of dynamic binary. In the BinaryDataEncoding.java file, it mentions to do this with another parameter. Can you provide an example on how to do this?

**Comment by xpromache** [comment]
I think in XTCE it should work by using SizeInBits element set to a dynamic value - however this is not supported by Yamcs :(

**Comment by JoshSharpe** [comment]
So is there a bridge at all or do you have to use excel to have dynamic binary sets?

**Comment by xpromache** [comment]
We also have custom binary algorithms but again I don't know how/if can
work from XTCE. I'm afraid for the moment the only option is excel :(

But don't lose hope, I'm sure it's not very difficult to implement so
hopefully it will be done soon :)

nicolae

**Comment by xpromache** [comment]
Maybe you will spend too much time with that, so if you want to help, the
quickest is to modify the BogusSAT-2.xml and also add a corresponding test
in BogusSat2Test.java  and I will get the test passing.

https://github.com/yamcs/yamcs/blob/master/yamcs-core/src/test/resources/xtce/BogusSAT-2.xml
https://github.com/yamcs/yamcs/blob/master/yamcs-core/src/test/java/org/yamcs/xtceproc/BogusSat2Test.java
<https://github.com/yamcs/yamcs/blob/49fa975efd717e23ebb967e0e22e9fef0f702c14/yamcs-core/src/test/java/org/yamcs/xtceproc/BogusSat2Test.java>

nicolae

**Comment by JoshSharpe** [comment]
Thank you. I'll get back to this in a few weeks.

**Comment by xpromache** [comment]
On the master branch (part of the next release) I pushed some code to make Yamcs work with algorithms in the data decoders/encoders and also added two algorithms that do the binary encoding/decoding with leading size.

An example can be found here:
https://github.com/yamcs/yamcs/blob/master/yamcs-core/src/test/resources/xtce/ref-xtce.xml
