### ISSUE TITLE
Support for segmented telemetry SpacePackets using Sequence Flags

### ISSUE THREAD

**Issue by AdamElliott-AB** [yamcs/yamcs#398]
https://public.ccsds.org/Pubs/133x0b1c2.pdf 4.1.2.4.2 describes using the SequenceFlags field in the CCSDS SpacePacket header to indicate that a packet is part of a larger set of user data. If a telemetry packet is segmented this way, does yamcs support assembling the segment-packets together before processing? If not, is this a feature that can be added?

**Comment by xpromache** [comment]
Sequence flags from CCSDS packets are not supported; I haven't heard of
anyone using that feature.
What is usually done is multiplexing packets inside CCSDS frames (AOS or
TM) and  Yamcs supports assembling packets across frames.

**Comment by AdamElliott-AB** [comment]
Thank you for your response. I appreciate the swift feedback.
