### ISSUE TITLE
Telemetry items in custom telemetry list link back to MDB listing not "live view"

### ISSUE THREAD

**Issue by trgarvey** [yamcs/yamcs#408]
When a custom telemetry list file (.par file) is created in the YAMCS server web interface, clicking on a live telemetry item in the .par list does not link back to the "details" view of the parameter as it does in the standard telemetry menu.  Instead, it links back to the Mission Database record of that telemetry item.  It would be much more useful if clicking on the item linked to the detailed live view so that a plot, etc. could be viewed as this is why a custom parameter list would typically be made- to view a specific list of live items during a mission.

**Comment by fqqb** [comment]
This dates back from when we only had the MDB pages.
Thanks for the report. Fixed on master branch.
