### ISSUE TITLE
No data returned when using pos >= limit in Get Table Data API call

### ISSUE THREAD

**Issue by mmgupta713** [yamcs/yamcs#427]
When I execute the following API call no data is returned:
http://localhost:8090/api/archive/simulator/tables/tm/data?limit=100&pos=100&order=asc
There are more than 200 rows in the tm table, so I'm expecting this to get 100 rows worth of data, but 0 rows worth of data is returned.

**Comment by xpromache** [comment]
Thanks for the report. Apparently there was a bug in that limit interpretation. It's fixed now.

Please note that you can get telemetry packets using a higher level API:
https://yamcs.org/docs/yamcs-http-api/packets/
