### ISSUE TITLE
There is no way to view all array values for <ArrayParameterType> parameters in the web UI

### ISSUE THREAD

**Issue by merose** [yamcs/yamcs#439]
When viewing a parameter which has an `<ArrayParameterType>` type definition in the XTCE, there is no way to view all array values in the Yamcs web UI. For example, here is a view of an array parameter that has 32 array elements. As can be seen, only the first 5 array elements are shown, and there is no way to get details to show the rest of the array values.

<img width="665" alt="image" src="https://user-images.githubusercontent.com/1649381/92008302-d902b080-ecfb-11ea-8f19-5eb1ed9013ef.png">

**Comment by merose** [comment]
There also appears to be no way to plot array values.

**Comment by merose** [comment]
It *is* possible to view array values by manipulating the URL in the web UI. By adding "[21]" to the URL we can see the array value and also plot the value. The URL is now "http://localhost:8090/telemetry/parameters/%2FViperRover%2FNss%2Fdetector1PulseHeights%5B21%5D/summary?c=viper__realtime". However, the parameter type appears to be incorrect. It shows `integer[]`, which is the type for the entire array, rather than `integer`.

<img width="655" alt="image" src="https://user-images.githubusercontent.com/1649381/92008751-66de9b80-ecfc-11ea-8746-29be5240da14.png">

**Comment by fqqb** [comment]
Closing as I think all of this has been addressed by now via various commits.
