### ISSUE TITLE
List Space Systems API should return alias set and ancillary data

### ISSUE THREAD

**Issue by merose** [yamcs/yamcs#444]
For some clients it is useful to be able to construct an abbreviation to the qualified name for a parameter. For example, a hypothetical rover might have a parameter hierarchy that looks like this. ("(A)" is used to mark aggregate types.)

    Rover
        Mobility
            Motors
                FrontLeftWheel (A)
                    velocity
                    torque
                FrontRightWheel (A)
                    velocity
                    torque

The "name" of the velocity parameters is not enough to distinguish them in a client view, while the full qualified names are quite long. (`/Rover/Mobility/FrontLeftWheel/velocity`, for example.) A strategy that we have used for other missions is to define abbreviations for MDB nodes that can be concatenated to form an abbreviation. For the front left velocity, for example, that might be `R_MOB_FL_velocity`. (Somewhat ugly, but usable.)

Using XTCE we might define these abbreviations using an `<AliasSet>`. Currently the List Space Systems API does not return alias sets for SpaceSystem elements, however. It would be convenient if alias sets and ancillary data sets were returned, as they are for List Parameters.

**Comment by fqqb** [comment]
On master
