### ISSUE TITLE
CCSDS max packet size as option / configureable

### ISSUE THREAD

**Issue by nmaas87** [yamcs/yamcs#457]
Hi there,

we sometimes got really large CCSDS packets which are over the currently hard configured max size (1500 Bytes) - so we have to change this here and compile Yamcs Server by ourselves. It would make sense to make MAX_CCSDS_SIZE somewhat configureable by a Yaml File, if possible:

https://github.com/yamcs/yamcs/blob/a58f39d8d4e9a28f566f052e271d163e76b8c619/yamcs-core/src/main/java/org/yamcs/tctm/CcsdsPacket.java#L10

Also, sometimes we got different sized CCSDS Headers (i.e. 6 instead of 16 bytes), so it would make sense to make a new constant, i.e. CCSDSHDRSIZE and use it on the construction of the ccsdshdr byte array, as well as the hardcoded 
16 - ccsdshdroffset
if ((len < 16) || len > CcsdsPacket.MAX_CCSDS_SIZE) {
res = inputStream.read(buffer, 16, len - 16);
and
throw new IOException("CCSDS packet body short read " + res + "/" + (len - 16));
parts within the same file...

https://github.com/yamcs/yamcs/blob/a58f39d8d4e9a28f566f052e271d163e76b8c619/yamcs-core/src/main/java/org/yamcs/tctm/TmFileReader.java#L68

It would also be cool if the CCSHDRSIZE would be configurable via Yaml, so that we won't have to rebuild every Yamcs Release ourselves / include these changes manually 👍🏻

**Comment by nmaas87** [comment]
( I posted to fast, so now there is even some text in the issue, instead of only some position in text )

**Comment by xpromache** [comment]
The TmFileReader class is very specific to the USOC/ISS setup, and should
be gone from Yamcs core;  it expects packets in very specific formats.

Data links such as FilePollingTmDataLink should be rewritten to use the
configurable packet preprocessors like the other data links.

**Comment by nmaas87** [comment]
Thanks for your answer - this is however specific to the TmFileReader class. I understand we can generate our own preprocessors to create own data links.

However, is it possible to make the parameter MAX_CCSDS_SIZE as a default to 1500 - but configurable via YAML so that we could adopt it other payload needs without having to recompile the whole server ourselves? I guess that FilePollingTmDataLink should be adable with less hassle or am I wrong there? Thanks a lot for your time and effort 👍🏻

**Comment by xpromache** [comment]
TmFileReader is used from FilePollingTmDataLink and FileTmPacketProvider. I understand your use it in connection to FilePollingTmDataLink, right?

I think I will get rid of the FileTmPacketProvider (can be replaced with a python script sending TM from file) and make the FilePollingTmDataLink use the packetInputStream similar with what TcpTmDataLink does.

I will rename the TmFileReader into a UsocPacketInputStream - the peculiarity of this is that it can read packets in multiple formats (raw CCSDS, PaCTS and HRDP but the last two are not relevant for users outside ISS/Columbus) with auto detection of the format. On the other hand it makes some assumptions about the CCSDS packets which are not necessary correct outside the Columbus/ISS world. Ideally it should move to our yamcs-usoc package.

Then I can add the option for the CCSDS packet length on the UsocPacketInputStream but you can also use the other CcsdsPacketInputStream or even the GenericPacketInputStream which can parse other types of packets.

**Comment by xpromache** [comment]
I pushed the changes above in the branch tm-file-reader-refactor, I suggest you give it a try.
I will merge it to the master one of these days.

**Comment by nmaas87** [comment]
Hey Nicolae,

thank you very much for your hard work. It makes sense to bundle all USOC/ISS specific links at one place and give the generic ones more flexiblity. I think that will make things a lot easier to implement without needing to modify the "core" Yamcs. Thank you :)
