### ISSUE TITLE
All commands are not visible in Command stack

### ISSUE THREAD

**Issue by navin-arl** [yamcs/yamcs#489]
Hi, 

There appears to be an issue while trying to add commands to the stack from yamcs-web when the number of commands in the MDB is greater than what can be displayed on a single page (Displayed at MDB/Commands in the web interface). Consequently, any command which is present on subsequent pages will not be displayed in the stack editor and hence cannot be added.

Additionally it might make sense to add a search bar to the stack editor so that commands can be found easily in case of a large MDB.

**Comment by fqqb** [comment]
Fixed on master.
Used the opportunity to add a few more stack-related niceties too.
