### ISSUE TITLE
Rendering Nested Aggregate Types in YAMCS WebApp

### ISSUE THREAD

**Issue by lorenzo-gomez-windhover** [yamcs/yamcs#493]
Hi there,

hope you are all doing well.

Not sure if you guys are aware of this, but it looks like the webapp does not construct the parameter path that gets sent to YAMCS server correctly when it is an AggregateType inside of another Aggregate Type:

![Screenshot from 2021-01-20 14-16-33](https://user-images.githubusercontent.com/68551873/105230072-784d0680-5b2a-11eb-8a41-fc4f8bfb8a25.png)

As you can see when I click on `AppInfo`, which is an Aggregate Type inside of the `Payload` AggreggateType, it gives the following error:

```
 157: Responding '404 Not Found': Nonexistent array/aggregate path in name cfs/cfe_es/CFE_ES_OneAppTlm_t.AppInfo
```

As you can tell it makes sense it failed; `cfs/cfe_es/CFE_ES_OneAppTlm_t.AppInfo` is incorrect. It should be `cfs/cfe_es/CFE_ES_OneAppTlm_t.Payload.AppInfo`

I tried my best to fix this myself on webapp, but honestly couldn't do it due to my lack of experience with the APIs you guys use. It looks like it has something to do with the following snippet of code on `ParameterSummaryTab.ts`:

```

  changeParameter(qualifiedName: string) {
    this.yamcs.yamcsClient.getParameter(this.yamcs.instance!, qualifiedName).then(parameter => {
      this.parameter$.next(parameter);

      if (this.parameterValueSubscription) {
        this.parameterValueSubscription.cancel();
      }
      this.parameterValueSubscription = this.yamcs.yamcsClient.createParameterSubscription({
        instance: this.yamcs.instance!,
        processor: this.yamcs.processor!,
        id: [{ name: qualifiedName }],
        abortOnInvalid: false,
        sendFromCache: true,
        updateOnExpiration: true,
        action: 'REPLACE',
      }, data => {
        this.parameterValue$.next(data.values ? data.values[0] : null);
      });
    });
  }
```

The `qualifiedName` value is incorrect at this point; it is `cfs/cfe_es/CFE_ES_OneAppTlm_t.AppInfo`, which is  the incorrect path.

Hope I explained the issue clear enough.

Any ideas on how to fix this?

Thanks
Lorenzo

**Comment by fqqb** [comment]
Indeed, nested aggregates and arrays are a bit tricky API-wise due to the type being shared for all members. And this particular page was never tested with it. I'll investigate a fix.

**Comment by lorenzo-gomez-windhover** [comment]
Thanks!

**Comment by lorenzo-gomez-windhover** [comment]
Tested the new changes. This is awesome! Thanks :+1: ! Will wait till it is merged into `master` to close issue.

**Comment by fqqb** [comment]
Thanks for verifying. We usually close if resolved on master (it is now). If there's any further bug, do say, and we'll reopen/fix.
