### ISSUE TITLE
edit alarm with "state": "unacknowledged" returns BadRequestException error

### ISSUE THREAD

**Issue by nikhilmandlik** [yamcs/yamcs#497]
As per [edit alarms documentation ]( https://docs.yamcs.org/yamcs-http-api/alarms/edit-alarm/) state can be `unacknowledged` but response returns with `BadRequestException`

### Sample request:
```
{
    "state": "unacknowledged",
    "comment": "testing unacknowledged"
}
```
### Response:
```
{
    "code": 400,
    "type": "BadRequestException",
    "msg": "Unsupported state 'unacknowledged'"
}
```

**Comment by xpromache** [comment]
I see the documentation is wrong. The code accepts these states:
acknowledged, shelved, unshelved or cleared

Once it's acknowledged, an alarm cannot be unacknowledged.

But shelving means to make it quiet for a time and it will either come back after that time or can be manually unshelved.
