### ISSUE TITLE
CFDP Incoming Transaction Being Cancelled unexpectedly

### ISSUE THREAD

**Issue by melekajacob** [yamcs/yamcs#506]
Hello, I'm having this problem where in the middle of an incoming CFDP transaction, all the incoming packets now are "UNEXPECTED_CFDP_PACKET". See the image below. This happens at different times during transfers, sometimes near the beginning, sometimes near the end.
![droppingTransfer](https://user-images.githubusercontent.com/23385706/106974190-4343d500-6722-11eb-9767-779920daf48c.png)

However, wireshark shows that the transaction numbers are the same in the valid vs. unexpected packets. 
Good Packet (see its the same packet that was accepted by Yamcs):
![goodPacket](https://user-images.githubusercontent.com/23385706/106974543-e1d03600-6722-11eb-8e1d-e0759e1a25ff.png)
Unexpected Packet (This is the very next packet that wasn't expected):
![badPacket](https://user-images.githubusercontent.com/23385706/106974557-e694ea00-6722-11eb-8126-e4ce95f83b51.png)

I am on Ubuntu 18.04.05 LTS, and this is my CFDP configuration
![image](https://user-images.githubusercontent.com/23385706/106974744-396ea180-6723-11eb-8d6e-bf3ef43e9db9.png)

From what I'm seeing in the code, I believe the cause is the pending transfer being dropped, but I could be wrong
![code_pic](https://user-images.githubusercontent.com/23385706/106974960-a08c5600-6723-11eb-82f7-e68c78603071.png)
.

**Comment by xpromache** [comment]
Hello, I think you are running an old version of Yamcs, can you update to the latest (5.3.5)? I fixed a lot of CFDP issues recently.

**Comment by melekajacob** [comment]
I was using the 5.2.1 release, I tried resetting to 5.3.5 tag, and was experiencing the same issue

**Comment by xpromache** [comment]
Can you please post a log?
The log message from 5.3.5 should be a bit more detailed than 5.2.1 (that's
how I saw you were using an older version).

**Comment by melekajacob** [comment]
The logs seem similar, this is the commit I'm at (5.3.5 tag on master branch)
![image](https://user-images.githubusercontent.com/23385706/107241529-0f560180-69f9-11eb-9902-b6c06f6556bb.png)

And these are the logs I'm seeing
![image](https://user-images.githubusercontent.com/23385706/107243068-a5d6f280-69fa-11eb-92c1-f6b177a9b979.png)

**Comment by xpromache** [comment]
That is weird because according to this:
https://github.com/yamcs/yamcs/blob/yamcs-5.3.5/yamcs-core/src/main/java/org/yamcs/cfdp/CfdpService.java#L392

you should have also the header printed on that "Unexpected CFDP packet"
line.

If you go in the admin area from yamcs-web (http://localhost:8090/admin)
what do you see as yamcs version?

**Comment by melekajacob** [comment]
Ahh sorry our server was using the older yamcs-core version as a dependency, changing to 5.3.5 fixed this issue. Thank you so much for the help
