### ISSUE TITLE
Can a non-superuser manage buckets in the Web Interface?

### ISSUE THREAD

**Issue by AdamElliott-AB** [yamcs/yamcs#507]
Can a non-superuser manage buckets in the Web Interface? I see the bucket management page in the "Admin Area" but this is only available to super users, correct?

**Comment by fqqb** [comment]
True, I agree this location is not ideal. Before, they were under the instance, but with buckets usually having global scope that was also not a good a place.

I'll move them to a separate section.

**Comment by fqqb** [comment]
On master
