### ISSUE TITLE
CustomAlgorithm should allow whitespace after closing parenthesis

### ISSUE THREAD

**Issue by merose** [yamcs/yamcs#513]
Currently some algorithm text that looks OK will generate parse errors when using `<CustomAlgorithm>` in XTCE. As an example, this parses fine:

        <CustomAlgorithm name="CombineImageChunks">
          <AlgorithmText language="Java">gov.nasa.viper.yamcs.algorithm.GenericAlgorithm(
              algorithm: gov.nasa.viper.yamcs.images.ImageAggregator
              dir: storage/images/chunks/cam0_jpeg
              )</AlgorithmText>
          ...
        </CustomAlgorithm>

However, adding whitespace before the closing `</AlgorithmText>` causes Yamcs not to start:

        <CustomAlgorithm name="CombineImageChunks">
          <AlgorithmText language="Java">gov.nasa.viper.yamcs.algorithm.GenericAlgorithm(
              algorithm: gov.nasa.viper.yamcs.images.ImageAggregator
              dir: storage/images/chunks/cam0_jpeg
              )
          </AlgorithmText>
          ...
        </CustomAlgorithm>

The Yamcs exception is:

    17:13:14.823 _global [1] YamcsServer Instance viper failed: java.lang.IllegalArgumentException: Cannot parse algorithm text 'gov.nasa.viper.yamcs.algorithm.GenericAlgorithm(
              algorithm: gov.nasa.viper.yamcs.images.ImageAggregator
              dir: storage/images/chunks/cam0_jpeg
              )
          '
	org.yamcs.algorithms.JavaAlgorithmExecutorFactory.makeExecutor(JavaAlgorithmExecutorFactory.java:24)
	org.yamcs.algorithms.AlgorithmManager.activateAlgorithm(AlgorithmManager.java:235)
	org.yamcs.algorithms.AlgorithmManager.loadAlgorithm(AlgorithmManager.java:148)
	org.yamcs.algorithms.AlgorithmManager.init(AlgorithmManager.java:124)
	org.yamcs.Processor.init(Processor.java:179)
	org.yamcs.ProcessorFactory.create(ProcessorFactory.java:101)
	org.yamcs.ProcessorFactory.create(ProcessorFactory.java:74)
	org.yamcs.ProcessorCreatorService.init(ProcessorCreatorService.java:48)
	org.yamcs.YamcsServer.initServices(YamcsServer.java:217)
	org.yamcs.YamcsServerInstance.doInit(YamcsServerInstance.java:145)
	org.yamcs.YamcsInstanceService.initAsync(YamcsInstanceService.java:62)
	org.yamcs.YamcsServerInstance.init(YamcsServerInstance.java:120)
	org.yamcs.YamcsServer.addInstance(YamcsServer.java:583)
	org.yamcs.YamcsServer.addGlobalServicesAndInstances(YamcsServer.java:1258)
	org.yamcs.YamcsServer.prepareStart(YamcsServer.java:1089)
	org.yamcs.YamcsServer.main(YamcsServer.java:891)

**Comment by xpromache** [comment]
Fixed on master.
