### ISSUE TITLE
Cannot download historical data of aggregate member in Yamcs web UI

### ISSUE THREAD

**Issue by merose** [yamcs/yamcs#521]
To reproduce.

1. In the Yamcs web UI, view a telemetry parameter that is an `<AggregateParameterType>` that has a member that is numeric. (In our case the aggregate is called `camState` and the member is `azimuth`.)
2. Click the link for the aggregate member.
3. Go to the Historical Data tab to view recent historical data for the aggregate member.
4. Click Download Data.

Expected result: Parameter data is downloaded as a textual table.
Actual result: Download fails. Error log in Yamcs console is below.

    16:03:52.480 _global [44] RouteHandler 164: Responding '400 Bad Request': Invalid parameter name specified /ViperRover/PanTiltUnit/camState.azimuth
    16:03:52.480 _global [44] HttpRequestHandler 58a6a9ff GET /api/archive/viper:exportParameterValues?parameters=/ViperRover/PanTiltUnit/camState.azimuth&start=2021-02-25T23:03:44.292Z&stop=2021-02-26T00:03:44.292Z 400

Screen shot of the Historical Data tab

<img width="1211" alt="image" src="https://user-images.githubusercontent.com/1649381/109236038-afdf4c00-7783-11eb-8ee0-8ac1548f4085.png">

**Comment by fqqb** [comment]
Thanks. Fixed on master.
