### ISSUE TITLE
User permissions for CFDP

### ISSUE THREAD

**Issue by AdamElliott-AB** [yamcs/yamcs#528]
Should be able to restrict which users are allowed to initiate file uploads via CFDP, access downloaded files, etc. Any estimate on when this feature will be added?

**Comment by xpromache** [comment]
>  Any estimate on when this feature will be added?

If you make a pull request, it will be soon...

It should not be very difficult; we can start with a general ControlFileTransfers privilege - to be added to SystemPrivileges.java and to be checked in FileTransferApi#verifyService.

**Comment by fqqb** [comment]
On master.
All file transfer calls require the system privilege `ControlFileTransfers`
