### ISSUE TITLE
Yamcs server manual and sample config should remove SystemParametersProvider

### ISSUE THREAD

**Issue by merose** [yamcs/yamcs#533]
The processor service org.yamcs.parameter.SystemParametersProvider has been removed, but it is referred to in two places:

1. [The server manual "processors" section](https://docs.yamcs.org/yamcs-server-manual/processors/system-parameter-provider/)
2. [distribution/etc/processor.yaml.sample](https://github.com/yamcs/yamcs/blob/master/distribution/etc/processor.yaml.sample)

The problem is that because the class no longer exists, Yamcs will not start if the user tries to configure this service.

**Comment by xpromache** [comment]
Thanks, fixed on master.
