### ISSUE TITLE
CustomAlgorithm Workflow

### ISSUE THREAD

**Issue by lorenzo-gomez-windhover** [yamcs/yamcs#539]
Hi there,

So we have the following algorithm in our  xtce file:

```
            <xtce:AlgorithmSet>
            	<xtce:CustomAlgorithm name="TimeAlgo">
            		<xtce:AlgorithmText language="Java">com.windhoverlabs.yamcs.algorithms.CFETime$CFETime_Algorithm()</xtce:AlgorithmText>
            		<xtce:InputSet>
            			<xtce:InputParameterInstanceRef
            				parameterRef="CFE_TIME_DiagPacket_t.Payload.AtToneMET.Seconds"
            				useCalibratedValue="true">
            			</xtce:InputParameterInstanceRef>
            		</xtce:InputSet>
            		<xtce:OutputSet>
            			<xtce:OutputParameterRef parameterRef="Time_Output" />
            		</xtce:OutputSet>
            		<xtce:TriggerSet>
            			<xtce:OnParameterUpdateTrigger parameterRef="CFE_TIME_DiagPacket_t/Payload/AtToneMET" />
            		</xtce:TriggerSet></xtce:CustomAlgorithm>
            </xtce:AlgorithmSet>

```
I've been reading the YAMCS Algorithms API and there is apparently two important functions:
- `execute`
- `updateInput`

I know `execute` is called every time the triggered is activated. However, even though InputParameterInstanceRef points to 
`CFE_TIME_DiagPacket_t.Payload.AtToneMET.Seconds`, I still get the entire Payload structure.

Now I did find a workaround which I saw in the commit that solves #514 and it is the following:

```
	    protected void updateInput(int idx, InputParameter inputParameter, ParameterValue newValue) {
	    	
	    	//Have to use this to fetch members of aggregates. Weird, I know. Will talk to SpaceApp about it. 
            ParameterValue memberValue = AggregateUtil.extractMember(newValue, inputParameter.getParameterInstance().getMemberPath());
            System.out.println("param value-->"+ memberValue.getEngValue());
	    }
```

Now this works, but I suspect that if we wrote more algorithms, which we will, we will have this boiler plate code probably in a function somewhere. And I know some of this was discussed on #514, but it appears that the focus was on the `OutputParameterRef`, but we are more curious about the `InputParameterInstanceRef`.

Is passing the entire Structure(in this case `CFE_TIME_DiagPacket_t`) a design choice?
I was wondering if there are plans for making the updateInput workaround described above the default behavior?

It's not a big deal I think because we do have a decent workaround(and perhaps more flexibility this way?), but I was still wondering if this was a design choice?

Thanks
Lorenzo

**Comment by xpromache** [comment]
We did not have aggregates for a long time. The internal subscription works at parameter level (you cannot subscribe to aggregate members), that's why the update method gets the full parameters not the members.

I have recently introduced a class ActiveAlgorithm class;
I think your code that extracts the member could be moved there in the updateParameters method. You can give it a try if you want.

**Comment by lorenzo-gomez-windhover** [comment]
I see what you mean. I would love to add support for this, but at the moment it's not a priority. We should be able to do what we want to do in Studio scripts. Thanks so much for the help!

**Comment by xpromache** [comment]
There is an advantage of having values computed using algorithms on the server: the results are available to all clients (web, grafana) and are also saved in the archive.

The Studio scripts are great for doing display stuff (for example a little animation or adding some colors) but that's about it.
