### ISSUE TITLE
Not possible to specify a default value for a binary command argument

### ISSUE THREAD

**Issue by merose** [yamcs/yamcs#552]
If you specify an `initialValue` for a binary argument to a command, the initial value is not used properly. Instead, an object ID is shown in the "Send a Command" form field, and you have to delete that value and type a new value in order to enable the "Send" button. This is an example of what is shown:

<img width="570" alt="image" src="https://user-images.githubusercontent.com/1649381/115129458-fb032780-9f9a-11eb-9a1d-3ee2b0c2baac.png">

The use case for this is for custom, programmatically-generated fields to be inserted into the command, by specifying a binary argument type with a custom `ToBinaryTransformAlgorithm`. The only reason to specify an `initialValue` is to make the argument optional in the form. If there is another way to accomplish this, please let me know. I would prefer not to do this in the command postprocessor, because this custom field is specific to only a few commands. Right now we are using the `CfsCommandPostprocessor` unmodified.

_Workaround:_ Leave out the `intialValue` and require the users to type a zero into the command argument field.

**Comment by xpromache** [comment]
Fixed on master. 

I did a big refactoring of the way algorithms are run (and the way input data is passed around, see the new class ProcessingData). 

I think now it might be possible without too much effort to have algorithms running when sending a command to compute some parameters which are then inserted into the command. 

Upon discussing with the XTCE creators they draw my attention that you can define parameters in the <CommandMetaData> section of an XTCE file.
It is not explained clearly but somehow the intention is that those parameters are contextualized to the command (i.e. you can have multiple commands running in parallel each with its own value for those parameters).
So maybe the trick is to allow algorithms to use those parameters as outputs and that's how we know to trigger the algorithm when sending a command which uses them in the command container entry. 
Currently it is possible to use a parameter in a command container, but the command will use whatever value is available for that parameter at the moment of sending.

to be further thought of...
