### ISSUE TITLE
Cannot acknowledge alarms generated from events by EventAlarmServer

### ISSUE THREAD

**Issue by merose** [yamcs/yamcs#557]
Found in version: 5.4.5

To reproduce:

1. Enable alarm generation from events via `eventServer: enabled` in the processor.yaml config.alarm section.
2. Start Yamcs.
3. In _Events_, create an event of severity WATCH or higher. 
Expected and actual result: Event is created and generates an unacknowledged alarm visible in the Yamcs web UI.
4. Go to _Alarms_, select the alarm, and click _ACKNOWLEDGE_ in the info panel.
Expected result: Alarm is acknowledged.
Actual result: Alarm still shows as unacknowledged, and there are errors in the log:

```
16:32:41.699 _global [35] RouteHandler 18: Responding '404 Not Found': No active alarm named '/yamcs/event/User/'
16:32:41.701 _global [35] HttpRequestHandler 20012589 PATCH /api/processors/viper/realtime/alarms/yamcs/event/User//0 404
```

**Comment by fqqb** [comment]
Fixed as of v5.6.0, this was a little trickier than expected because these events do not have a type
