### ISSUE TITLE
Impossible to write unit tests for custom algorithm because of AlgorithmExecutionResult member visibility

### ISSUE THREAD

**Issue by merose** [yamcs/yamcs#576]
`AlgorithmExecutionResult` has three member variables:

---
    final List<RawEngValue> inputValues;
    final List<ParameterValue> outputValues;
    final Object returnValue;
---

However, they are all default scope, and there are no getters. It's very difficult to write a unit test for a custom algorithm, because the algorithm's `execute` method returns `AlgorithmExecutionResult`, and the unit test cannot access the members to perform verifications.

Either add getters for those members (preferred, I think) or change the scope to `public`.

(This was not a problem prior to Yamcs 5.5.x, because algorithms returned a parameter value list instead.)

**Comment by merose** [comment]
Workaround: Create an `innerExecute` method in your algorithm that returns a `List<ParameterValue>` like the old `runAlgorithm` used to return, and call that from unit tests instead. The `execute` method can then just `return new AlgorithmResult(innerExecute(...))`.

**Comment by fqqb** [comment]
On master (added getters).
