### ISSUE TITLE
Export Archive Data Options

### ISSUE THREAD

**Issue by jeffstjean** [yamcs/yamcs#578]
When exporting archive data from a display, it would be nice to have more options to configure the export in the dialog. The option I would most like to see is the selection of a delimiter (tabs, commas, etc).

Maybe being able to select which parameters will be exported in case someone doesn't want all of them?

<img width="505" alt="Screen Shot 2021-07-08 at 11 08 35 AM" src="https://user-images.githubusercontent.com/31709307/124946292-e86a1e80-dfdc-11eb-951d-da4e908562c2.png">

**Comment by fqqb** [comment]
On master. Made it possible to select between TAB, COMMA and SEMICOLON.
Did not add an option to select parameters. A parameter table is already a selection, so I was not very comfortable adding another selection on top.

I think longer term we should maybe have another page where you can prepare an export (without first needing to make a Parameter Table display), and then that page would allow such selection functionality.
