### ISSUE TITLE
Yamcs does not support initialValue on AggregateArgumentType

### ISSUE THREAD

**Issue by merose** [yamcs/yamcs#579]
The XTCE specification allows an _initialValue_ attribute on AggregateArgumentType members, but XtceStaxReader does not support that, making aggregate argument types less useful. Yamcs should support _initial_value_ as an attribute for argument type members.

**Comment by AdamElliott-AB** [comment]
We are also looking for this feature. Any updates?

**Comment by xpromache** [comment]
I will fix it in the following days.
