### ISSUE TITLE
HTTP API Issue Command with parameters

### ISSUE THREAD

**Issue by keck-in-space** [yamcs/yamcs#587]
Hello,

I am looking at the HTTP API and I need some help understanding the [Issue Command](https://docs.yamcs.org/yamcs-http-api/commands/issue-command/) call. How could I specify the parameters of the command with this call? I only see a way to state the command name.

Thank you!

**Comment by fqqb** [comment]
You can assign argument using the JSON request body:

    {"assignment": [{"name": "arg1", "value": "value1"}, {"name": "arg2", "value": "value2"}]}

The web page specifies the format of the request body in TypeScript format. If you intend to do more with HTTP API, it can also be useful to use your browser development tools and snoop on the calls that the Web UI does.

**Comment by keck-in-space** [comment]
Ah, I see it now. Thanks! If I have a binary argument is it supported somehow? I don't think JSON supports binary natively.

**Comment by fqqb** [comment]
It's strings only. You should pass as hex.

**Comment by keck-in-space** [comment]
OK. Great. Thank you. I will try this.
