### ISSUE TITLE
Authentication with processes run by ProcessRunner

### ISSUE THREAD

**Issue by merose** [yamcs/yamcs#608]
I would like to run Yamcs using authentication, and I'd like to run a program using ProcessRunner that will periodically create events in Yamcs using the Python API. However, it's unclear how that external program should authenticate. I would prefer not to embed authentication arguments in the command line configured in Yamcs. What is the best way to authenticate from a process spawned by ProcessRunner?

**Comment by merose** [comment]
Or is there a way to detect that the connection request is from the same machine, and assume default authentication credentials in that case?

**Comment by fqqb** [comment]
It seems that the external program could have some self-managed config on how to connect (?)

To avoid passwords, you could also delegate auth to a reverse proxy, like nginx or apache with RemoteUserAuthModule.
I've used this before to support things like certificate-based authentication from client scripts.
(see https://docs.yamcs.org/yamcs-server-manual/security/authmodules/remote-user/).

ProcessRunner could also be improved to allow setting custom environment variables. At least then they would not appear on the command line.

**Comment by fqqb** [comment]
> Or is there a way to detect that the connection request is from the same machine, and assume default authentication credentials in that case?

I think a custom AuthModule could do that (cfr. RemoteUserAuthModule for ideas).

**Comment by merose** [comment]
Closing this as the suggestions from @fqqb seem sufficient.
