### ISSUE TITLE
In Yamcs 5.6.0 send command UI is broken if enumerated arguments have initial values

### ISSUE THREAD

**Issue by merose** [yamcs/yamcs#654]
To reproduce:

1. Clone the latest yamcs/quickstart project (which uses Yamcs 5.6.0.
2. Add the SpaceSystem below to the end of src/main/yamcs/mdb/xtce.xml. It adds a single command with one enumerated argument that has an initial value.
3. Start Yamcs via `mvn yamcs:run`.
4. Open a browser to Yamcs, then navigate to Commanding > Send a Command.
5. Browse to the command `/myproject/Test/SetBatteryMode`, which has one enumerated argument, the `batteryMode`, with an initial value of `NORMAL`.

Expected result: Drop-down with the argument is shown in the dialog, with an initial value of NORMAL.

Actual result: Argument is omitted from the dialog. In addition, the Send button does not send the command.

Additional SpaceSystem to add to the bottom of src/main/yamcs/mdb/xtce.xml:

~~~
  <SpaceSystem name="Test">
    <CommandMetaData>
      <ArgumentTypeSet>
        <EnumeratedArgumentType name="BatteryMode">
          <EnumerationList>
            <Enumeration value="1" label="LOW_POWER"/>
            <Enumeration value="2" label="NORMAL"/>
          </EnumerationList>
        </EnumeratedArgumentType>
      </ArgumentTypeSet>
      <MetaCommandSet>
        <MetaCommand name="SetBatteryMode">
          <BaseMetaCommand metaCommandRef="MyProjectPacket">
            <ArgumentAssignmentList>
              <ArgumentAssignment argumentName="Packet_ID" argumentValue="4"/>
            </ArgumentAssignmentList>
          </BaseMetaCommand>
          <ArgumentList>
            <Argument argumentTypeRef="BatteryMode" name="batteryMode" initialValue="NORMAL"/>
          </ArgumentList>
          <CommandContainer name="SetBatteryMode">
            <EntryList>
              <ArgumentRefEntry argumentRef="batteryMode"/>
            </EntryList>
          </CommandContainer>
        </MetaCommand>
      </MetaCommandSet>
    </CommandMetaData>
  </SpaceSystem>
~~~

If you remove the `initialValue="NORMAL"` from the argument definition, it works as expected. It also works in Yamcs 5.5.7. Numeric arguments also don't seem to have the problem, just enumerated arguments. Also, this does not affect command submission from scripts, only the web UI.

Screen shots:

Send a command dialog with initialValue for the command argument
<img width="1542" alt="image" src="https://user-images.githubusercontent.com/1649381/158872163-19fba99c-421d-4c87-814c-a64ecaaa60d7.png">

Sending a command dialog without initialValue for the command argument
<img width="1542" alt="image" src="https://user-images.githubusercontent.com/1649381/158873069-6955bd29-ce44-44aa-a23e-5bc8f7476a61.png">

Additionally, there are Javascript errors in the console:
<img width="752" alt="image" src="https://user-images.githubusercontent.com/1649381/158873974-31499beb-d919-4617-a4f1-1f454a9f899e.png">

**Comment by fqqb** [comment]
Thanks, fixed on master.

With the provided XTCE example, Yamcs will then complain about missing encoding, but that's unrelated.
