### ISSUE TITLE
Command stacks allow editing command options, but the options are not persisted

### ISSUE THREAD

**Issue by merose** [yamcs/yamcs#681]
When editing a command stack you can set command options and they show up in the Yamcs web UI. But when saving the stack, the command options are not persisted.

After editing a command stack command to set the cop1Bypass command option to true:
![image](https://user-images.githubusercontent.com/1649381/170845752-fbe9ab05-da28-40b0-b3fa-ba5a510c7007.png)

After saving the command stack, going away from the page, and opening the command stack again, the command option is gone. It is not in the .xml file either.
![image](https://user-images.githubusercontent.com/1649381/170845778-39e7156a-a2f6-484b-b99f-401e85492b5e.png)

**Comment by fqqb** [comment]
Fixed on master
