### ISSUE TITLE
Top checkbox selects all data links even if links are filtered by the search box

### ISSUE THREAD

**Issue by merose** [yamcs/yamcs#692]
In the _Links_ page in Yamcs, you can filter the data links by typing a search string in the search box. There is also a checkbox in the header line that allows selecting or deselecting all data links. However, it should only affect the data links shown, if the data links are filtered by a search string. Currently it selects or deslects _all_ data links, even if some are filtered from view.

To reproduce:

1. Run the Yamcs quickstart project using `$ mvn yamcs:run`.
2. In the _Links_ tab, both data links should be enabled, udp-in and udp-out. Filter the links to show only udp-out by typing "udp-out" in the search box at the top.
3. Now that only the udp-out link is shown, click the checkbox in the header bar, next to "Name In Out".
4. Click _Disable_ at the top of the page.
5. Clear the search box by clicking the "X" at the right end.

Expected result: The udp-out link is disabled, but the udp-in link is still enabled.

Actual result: Both the udp-out and udp-in links are disabled.

## Discussion

If there are a lot of data links, such as, for example, when connecting to the Deep Space Network, when up to 24 ground station links could be configured for each SLE service, it is important to be able to filter the data links by a unique string, such as "dss12", say. The "select all" checkbox in the header bar is, then, an attractive option for enabling all of the filtered links with only a few clicks. The current behavior of the "select all" checkbox makes this very error prone, however, because you will affect data links that you cannot see.

**Comment by fqqb** [comment]
On master, also went over other list pages that had the same problem.
