### ISSUE TITLE
COP-1 sliding window width ("K") should be configurable

### ISSUE THREAD

**Issue by merose** [yamcs/yamcs#698]
Currently the sliding window width defaults to 10. It can be changed via the COP-1 HTTP API, but there is no way to configure the default value. It would be convenient to be able to configure the default in the data link configuration, as is done for initialClcwWait, cop1T1, and cop1TxLimit. The configuration name "slidingWindowWidth", while not agreeing with CCSDS terminology, would be understandable and would match the ITOS configuration setting, for example.

**Comment by xpromache** [comment]
Fixed by 44724004651860c9a6b72e4a95d42288389590b8
