### ISSUE TITLE
Missing text in exception for ArrayValue

### ISSUE THREAD

**Issue by merose** [yamcs/yamcs#746]
Minor problem. In ArrayValue.java there is an exception thrown if the array dimensions has zero length. But the exception message is not a complete sentence. (line 32)

~~~
            throw new IllegalArgumentException("The array has to be at least ");
~~~

**Comment by xpromache** [comment]
Fixed by https://github.com/yamcs/yamcs/pull/758/commits/44724004651860c9a6b72e4a95d42288389590b8
