### ISSUE TITLE
Frontend hh:mm:ss bounds for XtimeParameterType

### ISSUE THREAD

**Issue by Stavrenas** [yamcs/yamcs#760]
As you can see bellow, the user can enter values larger than:
- 24 for the hours segment
- 60 for the minutes segment
- 60 for the seconds segment
I can send the command without any problem. If this is the intended behaviour, feel free to close the issue.
![time_argument](https://user-images.githubusercontent.com/7922854/216769242-6b71098b-e816-460c-aef7-4413483f5f40.png)
The resulting unix date is simply the starting date plus `hours * 24 * 60 * 60  + minutes * 60 * 60  + seconds * 60`, so it's **not** *invalid* or *illegal*.

**Comment by xpromache** [comment]
Just a small remark: 60 is sometimes valid for seconds (when leap seconds are enabled). I know we try to avoid usage of leap-seconds in the front-end (by performing smearing) and moreover leap seconds will disappear in the future, but still maybe relevant for the past.

**Comment by fqqb** [comment]
Closing because I quite like the rollover.
