### ISSUE TITLE
Yamcs 5.7.11 web client has old protobuf definitions

### ISSUE THREAD

**Issue by merose** [yamcs/yamcs#768]
The current Yamcs release apparently has the wrong protobuf definitions. Some features of the web client do not work.

To reproduce:

1. Clone the quickstart project.
2. Start Yamcs via `mvn yamcs:run`.
3. Start the simulator via `python3 simulator.py`.
4. Go to the Yamcs web UI and browse to Telemetry > Parameters, then the parameter "/myproject/A". The parameter should be updating once per second.
5. Click "CHART" to see a plot of the parameter.

Expected result: The chart displays.
Actual result: Errors in the Yamcs console about missing fields in the protobuf definition, as shown below.

~~~
09:36:01.399 _global [32] FieldMaskTree Cannot find field ""avg"" in message type yamcs.protobuf.pvalue.TimeSeries.Sample
09:36:01.399 _global [32] FieldMaskTree Cannot find field ""max"]" in message type yamcs.protobuf.pvalue.TimeSeries.Sample
09:36:01.399 _global [32] FieldMaskTree Cannot find field ""min"" in message type yamcs.protobuf.pvalue.TimeSeries.Sample
09:36:01.399 _global [32] FieldMaskTree Cannot find field ""n"" in message type yamcs.protobuf.pvalue.TimeSeries.Sample
09:36:01.399 _global [32] FieldMaskTree Cannot find field "["time"" in message type yamcs.protobuf.pvalue.TimeSeries.Sample
09:36:01.399 _global [32] FieldMaskTree Cannot find field ""avg"" in message type yamcs.protobuf.pvalue.TimeSeries.Sample
09:36:01.399 _global [32] FieldMaskTree Cannot find field ""max"]" in message type yamcs.protobuf.pvalue.TimeSeries.Sample
09:36:01.399 _global [32] FieldMaskTree Cannot find field ""min"" in message type yamcs.protobuf.pvalue.TimeSeries.Sample
09:36:01.399 _global [32] FieldMaskTree Cannot find field ""n"" in message type yamcs.protobuf.pvalue.TimeSeries.Sample
09:36:01.399 _global [32] FieldMaskTree Cannot find field "["time"" in message type yamcs.protobuf.pvalue.TimeSeries.Sample
... lines omitted ...
~~~

**Comment by merose** [comment]
Yamcs 5.7.10 has the same problem.

**Comment by fqqb** [comment]
Indeed,  thanks for finding this. It's this line here: https://github.com/yamcs/yamcs/blob/master/yamcs-web/src/main/webapp/src/app/client/YamcsClient.ts#L1347

I will see Tomorrow at work before making a change.
