### ISSUE TITLE
Time drops milliseconds

### ISSUE THREAD

**Issue by mtan23** [yamcs/yamcs#795]
I created an AbsoluteTimeArgumentType of "timetype" and I set the offset to 0 and scale to 0.0000001 in my xml file where the user inputs a time in the format hh:mm:ss. When I input "2.33" in the seconds field for when I want the command to execute, the milliseconds value seems to be dropped when the command report is displayed after it is sent (becomes 2:00). Can this issue be fixed since Yamcs states that it supports milliseconds as well.

**Comment by mtan23** [comment]
@fqqb how would I add it manually?

**Comment by fqqb** [comment]
Not sure I understand the question. It will be addressed in next release.

**Comment by fqqb** [comment]
On master, for inclusion in next release.
