### ISSUE TITLE
Binary argument types do not display properly in the 5.8.2 web UI

### ISSUE THREAD

**Issue by merose** [yamcs/yamcs#796]
To reproduce:

1. Clone the Yamcs quickstart project.
2. In the quickstart project, add the SpaceSystem below to the bottom of src/main/yamcs/mdb/xtce.xml.
3. Start yamcs via `mvn yamcs:run`.
4. Log in to the Yamcs web UI.
5. Go to Commanding > Send a Command, then browse to the command /myproject/Test/Sample.

Expected result: The single command argument `binary` has a form field for typing in a value.
Actual result: The "binary" label for the command argument appears, but no form field, making it impossible to send the command.

![image](https://github.com/yamcs/yamcs/assets/1649381/fd477eec-dd48-49dc-a97a-6f2b563492c1)

The additional SpaceSystem to add to the bottom of src/main/yamcs/mdb/xtce.xml:

~~~
  <SpaceSystem name="Test">
    <CommandMetaData>
      <ArgumentTypeSet>
        <BinaryArgumentType name="Binary">
          <BinaryDataEncoding>
            <SizeInBits><FixedValue>16</FixedValue></SizeInBits>
          </BinaryDataEncoding>
        </BinaryArgumentType>
      </ArgumentTypeSet>
      <MetaCommandSet>
        <MetaCommand name="Sample">
          <ArgumentList>
            <Argument argumentTypeRef="Binary" name="binary"/>
          </ArgumentList>
          <CommandContainer name="SampleContainer">
            <EntryList>
              <ArgumentRefEntry argumentRef="binary"/>
            </EntryList>
          </CommandContainer>
        </MetaCommand>
      </MetaCommandSet>
    </CommandMetaData>
  </SpaceSystem>
~~~

## Workaround

You can still send a command with a binary argument using a Python script or a curl command. It appears that the problem is limited to the Yamcs web UI.

**Comment by fqqb** [comment]
Yes, I've seen this. It's another sign we should start adding some unit tests to yamcs-web for these basic functionalities.

Fix has been prepared and will be in my next PR. I want to include few other things too before then.

**Comment by fqqb** [comment]
On master, for inclusion in next release.
