### ISSUE TITLE
Long event messages do not word-wrap, requiring horizontal scrolling if messages are too long

### ISSUE THREAD

**Issue by merose** [yamcs/yamcs#826]
We are converting some messages from non-Yamcs ground systems into Yamcs events. Some of these messages are quite long, without embedded newlines. This causes the Event page to be wider than the browser window, necessitating horizontal scrolling, which hides the source and type columns from operators.

We have found the CSS snippet below to allow word-wrapping of the event messages. Consider something similar for the base CSS.

~~~
yamcs-web:
  # Make event messages word-wrap.
  extraHeaderHTML: "<style>
app-event-message span {
    white-space: normal;
}
</style>"
~~~

**Comment by fqqb** [comment]
Addressed in PR #827
Though using `pre-wrap` intstead of `normal` (I would like to preserve newlines, if they are there)
