### ISSUE TITLE
Two bugs related to application.properties

### ISSUE THREAD

**Issue by 0lionelzhang0** [yamcs/yamcs#845]
Edit: This was on version 5.8.8

### application.properties does not seem to support booleans
provideJvmVariables: bool (.yaml file)
bool = true (application.properties)

``` 09:40:57.165 _global [1] YamcsServer yamcs.myproject.yaml: services[5].args: provideJvmVariables is of type STRING, but should be BOOLEAN instead ```

### default value doesn't seem to work
yamcs-web
- tag: ${foo:bar}

- when neither foo or bar are defined in application.properties, the tag is "bar" (expected)
- when foo is defined as "barfoo", the tag is "barfoo" (expected)
- when foo is not defined and bar is defined as "foobar", the tag is "bar", when should be "foobar" (bug?)

Edit: From the documentation, the second "bug" may be the expected behavior, but this makes it such that you can't set a string with spaces as a default value I think

**Comment by fqqb** [comment]
For the first issue, I think you're just missing the variable syntax: `provideJvmVariables: ${bool}`

For the second issue, indeed it should become possible to have spaces inside the default value. That's a bug.

Semantically, I think a nested variable could be expressed like this,`${foo:${bar}}`. However, this will not work currently either.

**Comment by 0lionelzhang0** [comment]
Sorry about that first one! My mistake...

Thanks for looking into the second one, that would be helpful to have!

**Comment by fqqb** [comment]
Nesting issue addressed in PR #858

**Comment by fqqb** [comment]
Should all be good as of v5.9.x

**Comment by 0lionelzhang0** [comment]
Thank you!
