### ISSUE TITLE
Yamcs tries to send commands to bound SLE link even if not active

### ISSUE THREAD

**Issue by merose** [yamcs/yamcs#853]
To reproduce:
1. Set up SLE telecommand data link to require separate "enable" and "Start SLE."
2. Enable the data link, but do not "Start SLE."
3. Send a command.

Expected result: Command will fail because no available data link.
Actual result: Command apparently goes away with no error because of enabled data link.

**Comment by xpromache** [comment]
This is not the behavior I notice. The command fails uplinking and it shows as an error in the command history.
(there is a 5 seconds timeout configured by the parameter  waitForUplinkMsec - debatable if that parameter should apply or not  in this case)

The code is controlled by the function isUplinkPossible:
https://github.com/yamcs/yamcs-sle/blob/master/src/main/java/org/yamcs/sle/TcSleLink.java#L215

which checks for the SLE state = ACTIVE. If the link is enabled and bound the state would be READY not ACTIVE.
The state is visible normally in the link page in the right panel (see screenshot below). 

Can you please tell which version of everything you are using?

![image](https://github.com/yamcs/yamcs/assets/909383/57a8010c-5b09-4362-845d-9dddac47d260)
![image](https://github.com/yamcs/yamcs/assets/909383/9e5918b9-a43d-4a48-b9d5-9d5ef5b36687)
