### ISSUE TITLE
Large CFDP transfer eventually slowdown and timeout

### ISSUE THREAD

**Issue by FPS-wibou** [yamcs/yamcs#863]
To reproduce:
- Configure Yamcs to use CFDP class 2. We are using fairly high transfer rate (1Mbs)
- Upload a large (e.g. 75MB) file. We are using cFS as the uploader application.

Expected:  
File transfer at a steady state until completed.

Issue:
File transfer perform nominally until ~16MB mark after which performance start to gradually degrade.
CPU usage seems to increase steadily to eventually reach 100% of 1 CPU.

Eventually, uploader application throws a timeout, even though transfer is still ongoing in YAMCS at a very low pace.
Timeout typically occurs between 60MB and 75MB of the file being transfered.
If uploader application is closed at that point, file continues to transfer until completion. This seems to indicate data are queued on YAMCS side.
If left long enough, transfer eventually is successful and checksum matches.

Might be related to this bug as we also experience high CPU usage:
https://github.com/yamcs/yamcs/issues/860

Details:
- YAMCS 5.8.8

CfdpService settings:
- maxPduSize: 512
- sleepBetweenPdus: 1000
- inactivityTimeout: 30000
- buckets configured as "filesystem bucket"

**Comment by xpromache** [comment]
Closing in favor of #860
