### ISSUE TITLE
Exported data from parameter table in "Displays" is always tab-delimitted regardless of delimiter choice

### ISSUE THREAD

**Issue by 0lionelzhang0** [yamcs/yamcs#867]
Hello,

Whenever I try to use the "Export archive data" button for a parameter table in "Displays", it always results in a tab-delimited file even if I choose "Comma" or "Semi-colon".

Yamcs Version: 5.8.8

Thanks!

![image](https://github.com/yamcs/yamcs/assets/36424267/e6e501f9-b67f-4fbd-8bd5-3dfdc94a3923)

Resulting file
![image](https://github.com/yamcs/yamcs/assets/36424267/65c98d19-f93c-4ea0-90e1-7fefcda18a35)

**Comment by fqqb** [comment]
OK i see why. I will include a fix in next pull request.

**Comment by 0lionelzhang0** [comment]
Thank you!

**Comment by fqqb** [comment]
Addressed in 5.9.x
