### ISSUE TITLE
Array arguments missing from commands in yamcs-web

### ISSUE THREAD

**Issue by AdamElliott-AB** [yamcs/yamcs#906]
Array arguments of a command are missing from the "Send a command" page. Browser console shows error:
  "ERROR TypeError: Cannot read properties of undefined (reading 'ɵcmp')"

How to reproduce:
1. clone yamcs/quickstart
2. edit src/main/yamcs/mdb/xtce.xml to have a command with an Array type argument
3. run yamcs and try to configure the above command from "Send a command"

[xtce.txt](https://github.com/user-attachments/files/15995216/xtce.txt)

**Comment by AdamElliott-AB** [comment]
Bug seems to have been introduced in version 5.9.4
5.9.3 does not exhibit the problem

**Comment by AdamElliott-AB** [comment]
This was tested in chrome Version 126.0.6478.114 on Ubuntu

**Comment by fqqb** [comment]
Thanks, addressed in pending PR #906. The issue came from a circular import.

**Comment by AdamElliott-AB** [comment]
Thank you @fqqb
