### ISSUE TITLE
Typo in documentation (data types)

### ISSUE THREAD

**Issue by 0lionelzhang0** [yamcs/yamcs#907]
https://docs.yamcs.org/yamcs-server-manual/mdb/data-types/

![Screenshot from 2024-06-26 13-51-49](https://github.com/yamcs/yamcs/assets/36424267/65e250da-c082-4256-941c-ea51e17a0119)

"argument" should be "parameter"

**Comment by fqqb** [comment]
Thanks, addressed in pending PR #908
