### ISSUE TITLE
AbstractLink uses wallclock time for command acknowledgements instead of configured time service

### ISSUE THREAD

**Issue by merose** [yamcs/yamcs#915]
In change cc6911a6757 on Mar 19, the AbstractLink class changed in an unfortunate way. Its `getCurrentTime()` method previously retrieved the time from the configured time service, but now uses the TimeEncoding class to get the wallclock time instead. This makes it very difficult to simulate a mission time in the future, because all the command acknowledgements look stale. This used to work fine.

Was there some reason I don't understand to make this change? It seems problematic to call TimeEncoding.getWallclockTime() at all, unless there is some strong reason. Shouldn't every class use the configured time service? Or is there a way to configure the TimeEncoding class to use a simulated wallclock time?

-----
The use case: we need to simulate, in our test flight components and ground systems, a time matching the mission ephemeris so that solar system bodies are in the proper orientation, shadowing is correct, etc., for our expected mission period. (It is very time-consuming to create test data sets, so we can create them only for certain time windows, and we want everything to run as if that time window is actually the wallclock time.) We have been able to accomplish this by configuring a custom time service, but changes like that to AbstractLink make it more difficult.

It's possible my understanding of the time services in Yamcs is faulty, however. If there is some other way we should be overriding the wallclock - other than configuring our time service, that is - please let me know.

**Comment by xpromache** [comment]
The change is unfortunate indeed. I think it was not intentional, I will revert it back.
