### ISSUE TITLE
Yamcs 5.9.x disallows directory traveral in bucket paths - should be a configurable option

### ISSUE THREAD

**Issue by merose** [yamcs/yamcs#919]
For some deployments it is convenient to have file system buckets that use symbolic links to put the actual bucket location outside of the Yamcs installation, for example, to put the bucket on an NFS mount. Yamcs 5.9.x has changed to disallow directory traversal in FileSystemBucket.java. It would be nice if this prohibition were configurable so that symbolic links could be used in file system bucket paths.

**Comment by fqqb** [comment]
I think what you describe should always be allowed. PR #920  includes a fix, while preserving the traversal check.

**Comment by fqqb** [comment]
On master
