### ISSUE TITLE
yamcs-web feature request: hyperlinks for nested containers in mdb 

### ISSUE THREAD

**Issue by 0lionelzhang0** [yamcs/yamcs#922]
Hello,

Some members from our team were wondering if it would be possible to implement hyperlinks for nested container definitions. 

Currently in 5.9.8, when you open a container definition in MDB the nested containers are listed as plain text and not clickable. This makes it a little cumbersome to traverse through a container's definition.

Our XTCE looks something like this:

``` 
<ContainerSet>
	<SequenceContainer>
		<EntryList>
			<ContainerRefEntry containerRef="ContainerA" />	
```

![Screenshot 2024-08-02 094604 (1)](https://github.com/user-attachments/assets/2277588e-a17f-457f-86e3-540a79e6f9c2)

Thanks!
Lionel

**Comment by fqqb** [comment]
Indeed, shall add this.

**Comment by fqqb** [comment]
On master, and in v5.10.0
