### ISSUE TITLE
QoL feature request: "Now" button for time date picker for AbsoluteTimeArgumentType

### ISSUE THREAD

**Issue by 0lionelzhang0** [yamcs/yamcs#954]
Hello,

It would be nice if there was a "Now" button to automatically set to current time for AbsoluteTimeArgumentTypes.

Use cases:
- command for setting time on remote device
- scheduling command to execute at future time (for testing, we may sometimes schedule for 10-20 seconds in future)

![image](https://github.com/user-attachments/assets/f7e9a857-44ba-4001-85f9-0f5332d2529e)

Thanks!
Lionel

**Comment by fqqb** [comment]
On master
