### ISSUE TITLE
XtceTmExtractor Exception Processing Packet Due to Container Size Limit

### ISSUE THREAD

**Issue by SadLinux** [yamcs/yamcs#966]
I am encountering an issue with an XTCE file that contains ~1700 parameters. When processing telemetry data, I receive the following error:  
08:07:03.469 _global [29] XtceTmExtractor Exception processing packet : org.yamcs.mdb.XtceProcessingException: Could not extract parameter /STA/Computed 153 from container /STA/DSU at position 12000 because it falls beyond the end of the container. Container size in bits: 12000

I am able to receive telemetry data up to 12000 bits, but nothing beyond that. Since I am sending the packets locally, I am confident that MTU is not an issue.

Question: Is there a way to adjust the maximum container size to accommodate parameters beyond this limit?

Any guidance or suggestions on how to resolve this issue would be greatly appreciated.

**Comment by xpromache** [comment]
If you are using the udp link you can set an option
maxLength: <sizeInBytes>


https://docs.yamcs.org/yamcs-server-manual/links/udp-tm-data-link/

**Comment by SadLinux** [comment]
Thank you!
