### ISSUE TITLE
# A fatal error has been detected by the Java Runtime Environment: #

### ISSUE THREAD

**Issue by JohnAdam-123** [yamcs/yamcs#972]
I have encountered this JRE error when starting the server. Can I get help of how to solve this error.
![fatal error runtime JRE](https://github.com/user-attachments/assets/13870a65-c387-4736-a682-7efb0f1eff07)

Here is the command I used `./mvnw yamcs:run
`

**Comment by JohnAdam-123** [comment]
> This appears when using a 5.10.0-4 version on older computers but should be solved by Yamcs 5.10.5, please give it a try.

So where do I go and change the version, or do I update this?

**Comment by xpromache** [comment]
inside the pom.xml which I guess you have in the myproject directory.

**Comment by JohnAdam-123** [comment]
> inside the pom.xml which I guess you have in the myproject directory.

Yes, I have it. Let me change and run it again. I'll give you the feedback.

**Comment by JohnAdam-123** [comment]
> inside the pom.xml which I guess you have in the myproject directory.

Yes. The update of the version solved the problem from `<yamcsVersion>5.10.1</yamcsVersion>` to `<yamcsVersion>5.10.5</yamcsVersion>`

Thank you.
