### ISSUE TITLE
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.13.0:compile (default-compile) on project myproject:

### ISSUE THREAD

**Issue by JohnAdam-123** [yamcs/yamcs#974]
I was trying to compile the YAMCS file server so that I might be able to run the project into my computer, but I ran into this error. [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.13.0:compile (default-compile) on project myproject: Fatal error compiling: error: release version 21 not supported -> [Help 1]
Here is the command I used `. /mvnw compile ` and below is the screenshot output.
![apache error](https://github.com/user-attachments/assets/712bcac8-b8f1-48fb-a613-5cc9d377912b)

How do I solve this, any ideas please?

**Comment by xpromache** [comment]
make sure you install the jdk package:
apt install openjdk-21-jdk

**Comment by fqqb** [comment]
Also see output of `./mvnw -version`

**Comment by JohnAdam-123** [comment]
> make sure you install the jdk package: apt install openjdk-21-jdk

I managed to solve it. I had to change the jdk to 17, but also settings the environment path. Then I compiled it again.

**Comment by JohnAdam-123** [comment]
> Also see output of `./mvnw -version`

Okay.
