### ISSUE TITLE
Web UI enum bug when nested in array -> aggregate -> enum

### ISSUE THREAD

**Issue by 0lionelzhang0** [yamcs/yamcs#979]
Hello,

Yamcs version 5.10.5

We noticed a minor visual bug when viewing an enumeration parameter nested in an array -> aggregate -> enum. It only shows the number value instead of the string value.

![image](https://github.com/user-attachments/assets/4dc179f6-8628-42fe-bafe-3fb336bc5fbf)

![image](https://github.com/user-attachments/assets/34cfb0a4-c562-4c31-8abf-6b637652d0bb)

Cases that do work as expected (enum shows string value):
- array -> enum
- aggregate -> enum

Thanks,
Lionel

**Comment by 0lionelzhang0** [comment]
Ahhh yes it is, sorry about that!

**Comment by xpromache** [comment]
no problem. 
It's funny we discovered the same bug simultaneously - this bug has been there forever.
