### ISSUE TITLE
Websocket: Parameter Unsubscribe: Server keeps returning empty parameters on unsubscribe

### ISSUE THREAD

**Issue by xsmarty** [yamcs/yamcs#99]
Stub : 
        NamedObjectList paramList = YamcsWSClient.getSubscription("/YSS/MOONWALK/RS_LaserState", "/YSS/MOONWALK/RS_BatteryCharge", "/YSS/MOONWALK/BIO_HeartRate");
        WebSocketRequest wsr;
        if (sub == true){ wsr = new WebSocketRequest("parameter", "subscribe",paramList); }
        else        { wsr = new WebSocketRequest("parameter", "unsubscribe",paramList);}
        sub = !sub;
        webSocket.sendRequest(wsr);

On parameter unsubscribe, empty ParameterData is beeing serialised back from server. 
I should be getting nothing back.

**Comment by m-sc** [comment]
Fixed
